-- Seed: Fall 2026 schedule as published on the Blogger page (2026-09-28)
INSERT OR REPLACE INTO settings (key, value) VALUES ('tagline', 'Lexington''s award-winning community affairs show, with a heavy bent towards local issues surrounding the simple concept of “let''s be nice to each other.” How hard can it be?');
INSERT OR REPLACE INTO settings (key, value) VALUES ('airtime', 'Every Thursday, 10 a.m. – noon (Eastern)');
INSERT OR REPLACE INTO settings (key, value) VALUES ('station_name', 'WRFL-FM 88.1');
INSERT OR REPLACE INTO settings (key, value) VALUES ('station_url', 'https://wrfl.fm');
INSERT OR REPLACE INTO settings (key, value) VALUES ('facebook_url', 'https://www.facebook.com/mickjeffries');
INSERT OR REPLACE INTO settings (key, value) VALUES ('host_name', 'Mick Jeffries');
INSERT OR REPLACE INTO settings (key, value) VALUES ('logo_url', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj8JAq_RRsqT-DcNLHNJdcnVKYTPKcEW0sLvg5csjUZBUIBsQ-Yj2Zw18z_kYc2P9Nl3L08uVR_URxl-De_VFYkAqohw7HSrnKFJ5eNNN_Q0c6zSezlOmBoqkn_L4kN3BywFpoe_A/s400/TT-just-logo.png');
INSERT OR REPLACE INTO settings (key, value) VALUES ('current_season', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2026-08-27', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-08-27'), 0, 'guest', 'Young Entrepreneurship in KY', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-08-27'), 1, 'guest', 'Author Maryjean Wall', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-08-27'), 2, 'guest', 'Everly Brothers biographer Barry Mazor', 'https://www.amazon.com/Blood-Harmony-Everly-Brothers-Story/dp/0306831732', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-09-03', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-03'), 0, 'guest', 'Sarabeth Brownrobie, Carnegie Center', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-03'), 1, 'guest', 'Lexington Art League: Tales from the Near Side', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-03'), 2, 'guest', 'SCFA Expansive Sounds with Matt Gibson', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-09-10', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-10'), 0, 'guest', 'League of Women Voters', '', 'Nat''l Voter Reg. Day');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-10'), 1, 'guest', 'Kim Baird, Roots & Heritage Festival', 'https://rootsfestky.com/', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-10'), 2, 'guest', 'KY Theatre''s Twelve Lions Festival', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-10'), 3, 'guest', 'UK SA/VS', 'https://finearts.uky.edu/savs', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-09-17', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-17'), 0, 'guest', 'Uniting Voices Lexington', 'https://www.unitingvoiceslexington.org/', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-17'), 1, 'guest', 'Green Room Exchange Presents: Insun Park & Generals', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-17'), 2, 'music', 'Carnage the Executioner/TERRELL X & sevenQTRS', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-09-24', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-24'), 0, 'guest', 'Jad Abumrad of Radiolab!!', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-24'), 1, 'guest', 'Mecca Live Studio', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-09-24'), 2, 'guest', 'Southland Street Fair', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-10-01', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-01'), 0, 'guest', 'Musician Vanessa Davis', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-01'), 1, 'guest', 'League of Women Voters', '', 'Voter Reg. Deadline');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-01'), 2, 'guest', 'Musician Scott Whiddon', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-10-08', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-08'), 0, 'guest', 'Tree Week Lexington', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-08'), 1, 'guest', 'UK Dept of Theatre & Dance''s ANTIGONE', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-08'), 2, 'music', 'Cape Verdean singer Lucibela', '', 'on behalf of Greenroom Exchange');
INSERT INTO episodes (air_date, season) VALUES ('2026-10-15', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-15'), 0, 'guest', 'John Winters of PRHBTN', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-15'), 1, 'guest', 'CivicLex', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-15'), 2, 'music', 'Eric McM', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-10-22', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-22'), 0, 'guest', 'Sarabeth Brownrobie, Carnegie Center', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-22'), 1, 'guest', 'League of Women Voters', '', 'non-partisan canvass');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-22'), 2, 'guest', 'LexPhil "Heroes & Villains"', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-22'), 3, 'guest', 'Thriller', '', 'tent.');
INSERT INTO episodes (air_date, season) VALUES ('2026-10-29', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-29'), 0, 'guest', 'SCFA Presents: Bang On A Can All-Stars!', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-29'), 1, 'guest', 'League of Women Voters', '', 'early voting');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-10-29'), 2, 'guest', 'Filmmaker Daniel Freed', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-11-05', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-11-05'), 0, 'guest', 'Author Normandi Ellis', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-11-05'), 1, 'guest', 'Tahlsound''s Willie Nelson Tribute', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-11-05'), 2, 'music', 'Jewelweed', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-11-12', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-11-12'), 0, 'guest', 'UK Dept of Theatre & Dance''s "Almost Maine" by Peter Stone', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-11-12'), 1, 'guest', 'UK Fine Arts Professor Doreen Maloney', '', '');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-11-12'), 2, 'music', 'Outside the Spotlight', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-11-19', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2026-11-26', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-11-26'), 0, 'feature', 'A Very Emily Thanksgiving', '', 'A Trivial Thursdays Tradition!');
INSERT INTO episodes (air_date, season) VALUES ('2026-12-03', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-12-03'), 0, 'guest', 'Steve Johnson, New Song In The Bluegrass Choir', 'https://www.facebook.com/NewSongInTheBluegrass/', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-12-10', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2026-12-17', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2026-12-17'), 0, 'guest', 'Uniting Voices Lexington', 'https://www.unitingvoiceslexington.org/', '');
INSERT INTO episodes (air_date, season) VALUES ('2026-12-24', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2026-12-31', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2027-01-07', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2027-01-07'), 0, 'guest', 'Sarah Katzenmaier, Cardiac Crusade', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2027-01-14', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2027-01-21', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2027-01-28', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2027-02-04', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2027-02-04'), 0, 'guest', 'UK Dept of Theatre & Dance''s Collected Stories', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2027-02-11', 'Fall 2026');
INSERT INTO episodes (air_date, season) VALUES ('2027-02-18', 'Fall 2026');
INSERT INTO segments (episode_id, position, kind, name, url, note) VALUES ((SELECT id FROM episodes WHERE air_date='2027-02-18'), 0, 'guest', 'UK Dept of Theatre & Dance''s American Son by Jeremy Gillett', '', '');
INSERT INTO episodes (air_date, season) VALUES ('2027-02-25', 'Fall 2026');
